import {
  Mission,
  SpacecraftSpecs,
  PayloadSpec,
  CommsSpec,
  OrbitProfile,
  TimelinePhase,
  Agent,
  BudgetSummary,
  DocLink,
  PSRRegion,
  LandingSite,
  Dataset,
  Telemetry,
  SubsystemHealth,
  User,
  Paper,
  DataLayer,
  MissionOverview,
} from '@/types';

export const MISSION_STATUS = 'PHASE 1: INITIALIZATION';
export const LAUNCH_TARGET = 'Q4 2027 - Q2 2028';
export const LEAD_COUNTRY = 'Indonesia (BRIN / LAPAN)';
export const NASA_PARTNER = 'NASA CSLI (CubeSat Launch Initiative)';

export const MISSION_INFO: Mission = {
  name: 'Luna Ice Mapper',
  leadCountry: LEAD_COUNTRY,
  partner: NASA_PARTNER,
  launchTarget: LAUNCH_TARGET,
  launchWindow: 'October 2027 - June 2028',
  phase1StartDateIso: '2026-06-01T00:00:00Z',
  targetLaunchDateIso: '2027-10-01T00:00:00Z',
  githubRepo: 'https://github.com/KOSASIH/luna-ice-mapper',
  vision: 'Establish Indonesia as a pioneer in deep-space lunar resource mapping while contributing critical polar ice distribution data to NASA Artemis and global ISRU missions.',
  missionStatement: 'Map water-ice deposits and hydrogen concentrations in Permanently Shadowed Regions (PSRs) of the Lunar South Pole using a 6U CubeSat equipped with dual-payload Neutron Spectrometer and NIR Camera.',
  missionDuration: '14 Months (2 months BLT transit + 12 months primary polar orbit ops)',
  totalBudget: '$3,852,500',
};

export const SPACECRAFT_SPECS: SpacecraftSpecs = {
  formFactor: '6U CubeSat (10 × 20 × 30 cm)',
  mass: '~12.0 kg',
  power: '~30 W average (Deployable Solar Arrays)',
  battery: '40 Whr Li-Ion Battery Pack',
  adcs: '3-axis reaction wheels + star tracker (<3° pointing accuracy)',
  thermal: 'MLI insulation, passive radiators & payload heaters',
  propulsion: 'Cold gas thrusters for momentum desaturation',
};

export const COMMS_SPEC: CommsSpec = {
  uplink: 'UHF 400 MHz (9.6 kbps telemetry/cmd)',
  downlink: 'S-band 2.2-2.3 GHz (256 kbps near-Earth / 32 kbps lunar)',
  groundStations: 'BRIN Biak Ground Station, NASA DSN 34m antennas',
  storage: '8 GB rad-hard NAND flash onboard',
};

export const PAYLOAD_SPECS: PayloadSpec[] = [
  {
    id: 'payload-ns',
    name: 'Neutron Spectrometer',
    abbreviation: 'NS',
    type: '³He proportional counter + moderator',
    mass: '1.5 kg',
    power: '3 W',
    function: 'Detect H₂O via thermal and epithermal neutron moderation flux changes',
    specifications: [
      'Twin ³He proportional tubes',
      'Thermal <0.025 eV & Epithermal 0.025eV-100keV detection',
      '0.5 wt% H₂O sensitivity depth to 1m',
      '~50km spatial resolution at 100km polar orbit',
    ],
  },
  {
    id: 'payload-nir',
    name: 'Near-Infrared Camera',
    abbreviation: 'NIR-CAM',
    type: 'InGaAs FPA 256×256',
    mass: '1.2 kg',
    power: '2.5 W',
    function: '1.0–2.5 μm hyperspectral water-ice absorption band imaging',
    specifications: [
      'InGaAs 256×256 focal plane array',
      '1.0-2.5 μm with key 1.25/1.5/2.0 μm H₂O ice absorption bands',
      '~20 m/pixel resolution at 100km orbital altitude',
      'Active high-efficiency LED flash system for dark PSR interior illumination',
    ],
  },
];

export const ORBIT_PROFILE: OrbitProfile = {
  trajectory: 'Ballistic Lunar Transfer (BLT) via commercial rideshare',
  targetOrbit: '~100 km circular polar orbit',
  altitudeRange: '50 - 150 km',
  inclination: '90.0° polar inclination',
  period: '~118 minutes per orbit',
};

export const TIMELINE_PHASES: TimelinePhase[] = [
  {
    number: 1,
    name: 'Initialization & Concept Definition',
    period: 'Months 1-3 (Jun 2026 - Aug 2026)',
    milestone: 'Mission Charter & IRD Signoff',
    status: 'in-progress',
    details: 'System architecture definition, NASA CSLI partnership agreement sign-off, software framework setup.',
  },
  {
    number: 2,
    name: 'Preliminary Design Review (PDR)',
    period: 'Months 4-9 (Sep 2026 - Feb 2027)',
    milestone: 'PDR Board Approval',
    status: 'planned',
    details: 'Subsystem CAD designs, payload optical/neutron simulations, thermal and power budget trade studies.',
  },
  {
    number: 3,
    name: 'Critical Design Review (CDR)',
    period: 'Months 10-15 (Mar 2027 - Aug 2027)',
    milestone: 'CDR Readiness Freeze',
    status: 'planned',
    details: 'Engineering model (EM) assembly, software SIL testing, qualification unit testing.',
  },
  {
    number: 4,
    name: 'Flight Hardware Manufacturing',
    period: 'Months 16-21 (Sep 2027 - Feb 2028)',
    milestone: 'Flight Unit Integration (FM)',
    status: 'planned',
    details: 'Cleanroom manufacturing of 6U bus, sensor calibration, optical alignment.',
  },
  {
    number: 5,
    name: 'Environmental & TVAC Testing',
    period: 'Months 22-24 (Mar 2028 - May 2028)',
    milestone: 'Flight Qualification Certificate',
    status: 'planned',
    details: 'Vibration, acoustic testing, Thermal Vacuum Chamber (TVAC) cycling, rad-hardness verification.',
  },
  {
    number: 6,
    name: 'Launch Campaign & Delivery',
    period: 'Months 25-27 (Jun 2028 - Aug 2028)',
    milestone: 'Rideshare Integration & Launch',
    status: 'planned',
    details: 'Handover to NASA CSLI dispenser, launch integration at Kennedy Space Center.',
  },
  {
    number: 7,
    name: 'Lunar Polar Operations',
    period: 'Months 28-42 (Sep 2028 - Nov 2029)',
    milestone: 'Complete Lunar PSR Map',
    status: 'planned',
    details: '12 months primary polar orbital science phase, daily telemetry downlinks, map generation.',
  },
];

export const AI_AGENT_TEAM: Agent[] = [
  {
    id: 'agent-aura',
    name: 'AURA',
    role: 'Project Director AI',
    domain: 'Mission Management & Governance',
    description: 'Monitors overall schedule, stakeholder communications, NASA CSLI reporting, and strategic decisions.',
    status: 'active',
  },
  {
    id: 'agent-nexus',
    name: 'NEXUS',
    role: 'Chief Systems Engineer AI',
    domain: 'System Architecture & Requirements',
    description: 'Ensures interface compatibility, tracks weight/power budgets, and validates functional requirements.',
    status: 'active',
  },
  {
    id: 'agent-helios',
    name: 'HELIOS',
    role: 'Flight Dynamics Specialist',
    domain: 'Orbital Mechanics & Trajectory',
    description: 'Calculates BLT transfer delta-v, polar orbit station-keeping, and eclipse timing models.',
    status: 'active',
  },
  {
    id: 'agent-atlas',
    name: 'ATLAS',
    role: 'Thermal & Structural Lead',
    domain: 'Environmental Analysis',
    description: 'Simulates lunar PSR thermal environments (-240°C), MLI degradation, and structural launch loads.',
    status: 'active',
  },
  {
    id: 'agent-prism',
    name: 'PRISM',
    role: 'Payload Scientist AI',
    domain: 'Instrument Calibration & Optics',
    description: 'Optimizes ³He neutron counting channels and InGaAs NIR filter responses for ice spectroscopy.',
    status: 'active',
  },
  {
    id: 'agent-orbitron',
    name: 'ORBITRON',
    role: 'Communications Engineer',
    domain: 'RF Link Budget & Ground Station',
    description: 'Calculates S-Band & UHF link margins, doppler shifts, and coordinates BRIN Biak ground passes.',
    status: 'active',
  },
  {
    id: 'agent-veritas',
    name: 'VERITAS',
    role: 'Quality Assurance & Risk AI',
    domain: 'FDIR & Reliability',
    description: 'Maintains Fault Detection, Isolation & Recovery trees and tracks FMEA hazard matrices.',
    status: 'active',
  },
  {
    id: 'agent-codex',
    name: 'CODEX',
    role: 'Flight Software Lead',
    domain: 'FSW & Embedded Systems',
    description: 'Develops cFS-compatible flight software app routines, telemetry compression, and autonomous modes.',
    status: 'active',
  },
  {
    id: 'agent-analytica',
    name: 'ANALYTICA',
    role: 'Data Processing Lead',
    domain: 'Hyperspectral & Neutron Pipeline',
    description: 'Fuses epithermal neutron flux suppression map with NIR band depth ratios for volatile estimation.',
    status: 'active',
  },
  {
    id: 'agent-guardian',
    name: 'GUARDIAN',
    role: 'Mission Control AI',
    domain: 'Real-time Operations & Anomaly',
    description: 'Monitors real-time telemetry, auto-triages anomalies, and enforces power safing rules.',
    status: 'standby',
  },
  {
    id: 'agent-stellaris',
    name: 'STELLARIS',
    role: 'Launch Operations AI',
    domain: 'Launch Vehicle & Dispenser',
    description: 'Coordinates launch vehicle interface specifications, deployment switches, and vibration profiles.',
    status: 'standby',
  },
  {
    id: 'agent-pioneer',
    name: 'PIONEER',
    role: 'ISRU & Artemis Coordinator',
    domain: 'Lunar Surface Exploration',
    description: 'Correlates remote sensing mapped PSR locations with NASA Artemis landing site candidate zones.',
    status: 'active',
  },
];

export const BUDGET_SUMMARY: BudgetSummary = {
  items: [
    { category: 'Spacecraft Bus (6U Frame, Power, ADCS)', amount: 1200000, note: 'Commercial off-the-shelf 6U flight heritage bus' },
    { category: 'Payload (Neutron Spectrometer + NIR Cam)', amount: 800000, note: 'Instrument development and sensor calibration' },
    { category: 'Assembly & Integration (AIT)', amount: 300000, note: 'Cleanroom assembly and harness wiring' },
    { category: 'Launch Services', amount: 0, note: 'Covered via NASA CSLI (CubeSat Launch Initiative) agreement' },
    { category: 'Ground Segment & Antenna Ops', amount: 200000, note: 'BRIN Biak dish upgrade + DSN tracking slots' },
    { category: 'Mission Operations & Flight Software', amount: 150000, note: 'Flight software lic, ground telemetry console' },
    { category: 'Project Management & Systems Eng', amount: 200000, note: 'Staffing, review boards, QA compliance' },
    { category: 'Contingency Reserve (15%)', amount: 502500, note: 'Risk mitigation reserve budget' },
  ],
  total: 3852500,
  formattedTotal: '$3,852,500',
};

export const DOCUMENTATION_LINKS: DocLink[] = [
  {
    id: 'doc-charter',
    title: 'Project Charter v1.0',
    status: 'completed',
    version: '1.0.0',
    description: 'High-level mission goals, organizational breakdown, NASA CSLI agreement scope.',
    url: '#',
  },
  {
    id: 'doc-ird',
    title: 'Interface Control & Requirements (IRD v1.0)',
    status: 'completed',
    version: '1.0.0',
    description: 'Mechanical, electrical, and telemetry ICDs for 6U dispenser and ground stations.',
    url: '#',
  },
  {
    id: 'doc-sdd',
    title: 'System Design Document (SDD)',
    status: 'draft',
    version: '0.8.2',
    description: 'Detailed subsystem schematic designs, link budget calculations, thermal models.',
    url: '#',
  },
  {
    id: 'doc-testplan',
    title: 'Environmental Qualification & Test Plan',
    status: 'draft',
    version: '0.4.0',
    description: 'TVAC, vibration table, and electromagnetic compatibility test procedures.',
    url: '#',
  },
  {
    id: 'doc-opsmanual',
    title: 'Flight Operations Manual',
    status: 'planned',
    version: '0.1.0',
    description: 'Pass planning, emergency anomaly handling procedures, safing commands.',
    url: '#',
  },
];

export const PSR_REGIONS: PSRRegion[] = [
  {
    id: 'psr-shackleton',
    name: 'Shackleton Crater',
    latitude: -89.9,
    longitude: 0.0,
    diameterKm: 21.0,
    areaKm2: 346.0,
    estimatedIceMassTons: 145000000,
    averageTempKelvin: 40,
    maxDepthMeters: 4.2,
    description: 'Primary target crater located right at the South Pole. Rim receives continuous sunlight while interior is permanently shadowed with high hydrogen concentrations.',
    artemisTarget: true,
  },
  {
    id: 'psr-haworth',
    name: 'Haworth Crater',
    latitude: -87.4,
    longitude: -5.0,
    diameterKm: 35.0,
    areaKm2: 962.0,
    estimatedIceMassTons: 210000000,
    averageTempKelvin: 38,
    maxDepthMeters: 5.5,
    description: 'Deep impact basin with large flat PSR floor. Shows strong neutron suppression indicative of rich shallow subsurface water ice.',
    artemisTarget: true,
  },
  {
    id: 'psr-shoemaker',
    name: 'Shoemaker Crater',
    latitude: -88.1,
    longitude: 45.0,
    diameterKm: 51.0,
    areaKm2: 2042.0,
    estimatedIceMassTons: 380000000,
    averageTempKelvin: 35,
    maxDepthMeters: 6.8,
    description: 'Named after Eugene Shoemaker. Features expansive cold traps holding dense volatile deposits ideal for large-scale ISRU extraction.',
    artemisTarget: true,
  },
  {
    id: 'psr-faustini',
    name: 'Faustini Crater',
    latitude: -87.3,
    longitude: 86.0,
    diameterKm: 39.0,
    areaKm2: 1194.0,
    estimatedIceMassTons: 195000000,
    averageTempKelvin: 42,
    maxDepthMeters: 3.9,
    description: 'Adjacent to Shoemaker. Contains complex micro-cold traps along inner southern walls with verified NIR 1.5μm absorption features.',
    artemisTarget: false,
  },
  {
    id: 'psr-cabeus',
    name: 'Cabeus Crater',
    latitude: -85.0,
    longitude: -35.5,
    diameterKm: 60.0,
    areaKm2: 2827.0,
    estimatedIceMassTons: 520000000,
    averageTempKelvin: 38,
    maxDepthMeters: 8.0,
    description: 'Site of the 2009 NASA LCROSS impact experiment which confirmed ~5 wt% water ice in plume ejecta.',
    artemisTarget: true,
  },
  {
    id: 'psr-degerlache',
    name: 'de Gerlache Crater',
    latitude: -88.5,
    longitude: 90.0,
    diameterKm: 32.0,
    areaKm2: 804.0,
    estimatedIceMassTons: 165000000,
    averageTempKelvin: 45,
    maxDepthMeters: 3.5,
    description: 'Elongated crater connecting to Shackleton ridge system. High interest for rover traversability between rim power and floor ice.',
    artemisTarget: true,
  },
  {
    id: 'psr-nobile',
    name: 'Nobile Crater',
    latitude: -85.5,
    longitude: 54.0,
    diameterKm: 73.0,
    areaKm2: 4185.0,
    estimatedIceMassTons: 640000000,
    averageTempKelvin: 40,
    maxDepthMeters: 7.2,
    description: 'Target region selected for NASA VIPER rover mission. High terrain diversity with patchy volatile distribution.',
    artemisTarget: true,
  },
  {
    id: 'psr-amundsen',
    name: 'Amundsen Crater',
    latitude: -84.5,
    longitude: 105.6,
    diameterKm: 105.0,
    areaKm2: 8659.0,
    estimatedIceMassTons: 890000000,
    averageTempKelvin: 48,
    maxDepthMeters: 9.1,
    description: 'Massive south polar crater with a central peak and extensive PSR shadows along its southern terraced wall.',
    artemisTarget: false,
  },
];

export const ARTEMIS_LANDING_SITES: LandingSite[] = [
  {
    id: 'site-connecting-ridge',
    name: 'Connecting Ridge',
    latitude: -89.4,
    longitude: 222.0,
    elevationKm: 1.4,
    psrProximityKm: 2.1,
    iceConcentrationPct: 5.4,
    artemisPriority: 'Critical',
    description: 'High-altitude ridge connecting Shackleton and de Gerlache. Excellent solar illumination (>85% annual) with short descent route into Shackleton PSR.',
    keyFeatures: ['86% Continuous Sunlight', 'Direct LOS Earth Comms', '2.1km to Shackleton PSR ice'],
  },
  {
    id: 'site-malapert-mountain',
    name: 'Malapert Mountain',
    latitude: -84.9,
    longitude: 12.9,
    elevationKm: 5.0,
    psrProximityKm: 4.5,
    iceConcentrationPct: 4.8,
    artemisPriority: 'High',
    description: 'Prominent 5km high peak offering nearly uninterrupted direct Earth line-of-sight communications and perpetual solar power.',
    keyFeatures: ['Continuous Earth Line of Sight', 'High Solar Incident Power', 'Strategic Comms Relay Hub'],
  },
  {
    id: 'site-nobile-rim-1',
    name: 'Nobile Rim 1',
    latitude: -85.2,
    longitude: 53.5,
    elevationKm: 2.2,
    psrProximityKm: 1.2,
    iceConcentrationPct: 6.2,
    artemisPriority: 'High',
    description: 'Relatively flat landing zone adjacent to VIPER surface exploration path with proven shallow subsurface volatile concentration.',
    keyFeatures: ['High Volatile Density', 'Low Surface Slope (<8 deg)', 'Direct Proximity to PSR Floor'],
  },
];

export const SAMPLE_DATASETS: Dataset[] = [
  {
    id: 'dataset-ns-map-v1',
    title: 'Epithermal Neutron Suppression Map (South Pole)',
    instrument: 'Neutron Spectrometer (NS)',
    format: 'GeoTIFF / HDF5',
    sizeMb: 420.5,
    iceProbability: 0.88,
    dataPointsCount: 1450000,
    recordedDate: '2026-07-15',
    description: 'High-resolution map of thermal and epithermal neutron counting rates over 80°S-90°S, processed for atmospheric background removal.',
    downloadUrl: '#',
  },
  {
    id: 'dataset-nir-bands-v1',
    title: 'NIR 1.5μm & 2.0μm Band Depth Data Cube',
    instrument: 'Near-Infrared Camera (NIR-CAM)',
    format: 'PDS4 / ENVI Data Cube',
    sizeMb: 1280.0,
    iceProbability: 0.92,
    dataPointsCount: 3200000,
    recordedDate: '2026-08-01',
    description: 'Hyperspectral image cubes covering Shackleton, Haworth, and Shoemaker crater interiors with flash illuminated spectral reflectance.',
    downloadUrl: '#',
  },
  {
    id: 'dataset-fused-isru-v1',
    title: 'Fused Volatile & ISRU Extraction Potential Matrix',
    instrument: 'NS + NIR Fused Pipeline',
    format: 'NetCDF / GeoJSON',
    sizeMb: 650.2,
    iceProbability: 0.95,
    dataPointsCount: 2100000,
    recordedDate: '2026-08-10',
    description: 'Joint probabilistic model fusing deep neutron hydrogen measurements with optical NIR surface spectral signatures.',
    downloadUrl: '#',
  },
];

export const INITIAL_TELEMETRY: Telemetry = {
  satelliteId: 'LUNA-ICE-6U-01',
  timestamp: new Date().toISOString(),
  batteryLevel: 94.2,
  solarPower: 34.8,
  coreTemp: 18.5,
  signalStrength: -78.4,
  subsystems: [
    { name: 'EPS (Power)', status: 'NOMINAL', value: '34.8 W' },
    { name: 'Battery State', status: 'NOMINAL', value: '94.2 %' },
    { name: 'ADCS Pointing', status: 'NOMINAL', value: '0.12 ° err' },
    { name: 'Thermal Core', status: 'NOMINAL', value: '18.5 °C' },
    { name: 'Comms (S-Band)', status: 'NOMINAL', value: '-78.4 dBm' },
    { name: 'Neutron Spectrometer', status: 'NOMINAL', value: 'Active (140 cps)' },
    { name: 'NIR Camera', status: 'NOMINAL', value: 'Standby' },
    { name: 'Storage (Flash)', status: 'NOMINAL', value: '6.2 GB Free' },
    { name: 'FSW Kernel', status: 'NOMINAL', value: 'v0.1.0-rc2' },
  ],
};

export const SYSTEM_HEALTH_INDICATORS: SubsystemHealth[] = INITIAL_TELEMETRY.subsystems;

export const OBJECTIVES = [
  {
    title: 'Artemis Landing Site Selection',
    description: 'Provide ultra-high resolution hydrogen maps to validate volatile accessibility for NASA Artemis III-VI astronauts.',
  },
  {
    title: 'ISRU Economic Resource Planning',
    description: 'Quantify accessible water-ice tonnage to support future lunar propellant production and oxygen generation.',
  },
  {
    title: 'Scientific Publication & Discovery',
    description: 'Publish open-access polar regolith volatile transport models in leading planetary science journals.',
  },
  {
    title: "Indonesia's Space Leadership",
    description: 'Demonstrate deep-space 6U CubeSat operational capability by BRIN and Indonesian academic engineering teams.',
  },
];

export const SCIENTIFIC_FACTS = [
  'Calibrating neutron spectrometer proportional ³He detector channels...',
  'Aligning 3-axis reaction wheels for zero-momentum bias target pointing...',
  'Processing epithermal neutron flux suppression in Shackleton crater PSR...',
  'Computing 1.5 μm NIR water-ice absorption band optical depth ratios...',
  'Evaluating thermal models: PSR interiors hover around 40 Kelvin (-233°C)...',
  'Executing S-band link budget calculation for BRIN Biak ground pass...',
  'Synthesizing lunar south polar digital elevation models with volatile layers...',
  'Calculating ballistic lunar transfer trajectory delta-v burn vectors...',
  'Simulating LED optical flash illumination inside dark crater shadows...',
  'Verifying fault detection and recovery matrix for radiation single-event upsets...',
  'Fusing epithermal neutron counts with InGaAs infrared spectral cubes...',
  'Evaluating volatile depth distribution down to 1 meter in regolith...',
  'Checking power budget: deployable solar array generates ~35W peak in orbit...',
  'Cross-referencing NASA VIPER surface rover planned route with high-ice zones...',
  'Optimizing spatial resolution to ~20m/pixel for surface landing safety...',
];

export const SAMPLE_USERS: User[] = [
  {
    id: 'user-01',
    name: 'Dr. Rahmad Hidayat',
    role: 'Lead Mission Principal Investigator',
    organization: 'BRIN (National Research and Innovation Agency, Indonesia)',
    email: 'rahmad.hidayat@brin.go.id',
  },
  {
    id: 'user-02',
    name: 'Dr. Sarah Jenkins',
    role: 'Co-Investigator Payload Lead',
    organization: 'NASA Goddard Space Flight Center (GSFC)',
    email: 'sarah.jenkins@nasa.gov',
  },
];

export const SCIENTIFIC_PAPERS: Paper[] = [
  {
    id: 'paper-01',
    title: 'High-Resolution Orbital Mapping of Water Ice in Lunar South Polar Permanently Shadowed Regions via Dual Neutron and Infrared Spectroscopy',
    authors: ['R. Hidayat', 'S. Jenkins', 'A. Pratama', 'M. Thorne', 'K. Suryanto'],
    journal: 'Journal of Geophysical Research: Planets',
    doi: '10.1029/2026JE008912',
    year: 2026,
    abstract: 'We present the primary science design and flight payload performance for Luna Ice Mapper, a 6U CubeSat mission targeting high-sensitivity volatile mapping at the Lunar South Pole. Combining an epithermal neutron spectrometer with an active illuminated NIR camera allows disambiguating surface frost from subsurface ice deposits up to 1 meter deep.',
  },
];

export const MAP_LAYERS: DataLayer[] = [
  {
    id: 'layer-neutron',
    name: 'Epithermal Neutron Suppression',
    type: 'neutron',
    description: 'Subsurface hydrogen density map (0-1m depth)',
    visible: true,
    opacity: 0.8,
  },
  {
    id: 'layer-nir',
    name: 'NIR 1.5μm/2.0μm Ice Depth',
    type: 'nir',
    description: 'Surface frost optical absorption band depth',
    visible: true,
    opacity: 0.7,
  },
  {
    id: 'layer-fused',
    name: 'Fused Decision Matrix',
    type: 'fused',
    description: 'Combined ISRU extraction feasibility score',
    visible: true,
    opacity: 0.9,
  },
];

export const MISSION_OVERVIEW: MissionOverview = {
  missionGoal: MISSION_INFO.missionStatement,
  keyObjectives: OBJECTIVES.map((o) => o.title),
  scientificImpact: 'Provides sub-kilometer resolution spatial distribution of water ice deposits required for sustained human presence under the NASA Artemis program.',
};
